### ISSUE TITLE
Valores repetidos en la DB

### ISSUE THREAD

**Issue by AARP41298** [developarts/cat_localidad#1]
Me encuentro con que 1 estado tiene 2 municipios repetidos, y las localidades de estos, NO SE REPITEN, creo que solo es cuestión de "unir" las localidades de los municipios repetidos

Los municipios son: San Juan Mixtepec y San Pedro Mixtepec

opino eliminar el 1218 y redirigir al 1217
de la misma forma, eliminar 1328 y redirigir al 1327

**Comment by AARP41298** [comment]
Que si había solo 2 municipios repetidos, NAMBRE, de localidades ni les digo
De las 300690 localidades, elimine los repetidos
exportando solo los datos que necesito de esta DB, los importe a mi proyecto actual con INSERT IGNORE, la tabla localidades ya creada con un unique en el municipio_id y el nombre (por que no puede haber más de 2 localidades en un municipio con el mismo nombre, o si?)

contando los registros, me quedo con solamente 273267 localidades

**Comment by developarts** [comment]
No estoy tan seguro del tema de las repeticiones. Te adjunto la base de datos del INEGI, y como puedes ver tiene 300690 líneas exactas.

![Fuente de Datos](https://user-images.githubusercontent.com/3060193/117171544-91ec2400-ad90-11eb-88ee-b52c61ef11ae.png)

Ya pasó un tiempo y debería de actualizar la información. En cuanto lo tenga te aviso en este hilo y lo revisamos. En la nueva versión tendremos 300629 localidades.

![Captura de Pantalla 2021-05-05 a la(s) 11 08 31 a m](https://user-images.githubusercontent.com/3060193/117173569-839f0780-ad92-11eb-87cc-429a0dec97ce.png)

**Comment by ChecoSchnaider** [comment]
Gracias!!! 

No lei bien y empece a separarla en estados, municipios y localidades. Cuando en INEGI sale todo en csv!! 

mil gracias!

**Comment by developarts** [comment]
Quedamos al pendiente. Muchas gracias.
